### ISSUE TITLE
Not matched result between data_post and recalcuate using perm_post

### ISSUE THREAD

**Issue by ramdhan1989** [tuda-geo/dageo#19]
Hi, 
Why data_post taken directly from esmda is different if I rerun the simulation (I used simulator)? Here is example, I used 2 realizations as shown by blue line it has very good match. However, if I take perm_post of first realization and use it in simulator, I got green line which is not matched.
![image](https://github.com/user-attachments/assets/45bc3961-fbd3-4d94-bf4f-702c4f669387)

Please advise,
thank you

**Comment by prisae** [comment]
Hi @ramdhan1989, thanks for reaching out. Hard to say from your description. Would it be possible that you paste the code here or somewhere else where we can have a look? (E.g., as a [gist](https://gist.github.com/) or similar.)

**Comment by prisae** [comment]
Did you resolve the issue, can we close this or do you want to put some code here so we can help?

**Comment by ramdhan1989** [comment]
Hi, yes it is resolved. Thanks for your help.
